id: P009234
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:17.044374
source_metadata:
  id: bdr:W1KG21018
  title: སྤྱི་ཚོགས་རིང་ལུགས་ཀྱི་དམངས་གཙོ་དང་ཁྲིམས་ལུགས་སྐོར་བཤད་པ།
  author: ''
  volumes:
    b55670b538ef451594c955a130fee5e5:
      image_group_id: I1KG21130
      title: ''
      volume_number: 1
      total_pages: 412
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
